# Generated by Django 6.0 on 2025-12-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='task id')),
                ('task_name', models.CharField(max_length=100, verbose_name='task name')),
                ('task_detail', models.TextField(blank=True, max_length=250, verbose_name='task detail')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
                ('complete_flag', models.BooleanField(default=False, verbose_name='complete flag')),
            ],
        ),
    ]
