# Generated by Django 6.0 on 2025-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_rename_taskname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='complete date'),
        ),
    ]
