# Generated by Django 6.0 on 2025-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suomi_app', '0003_task_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delete_flag',
            field=models.BooleanField(default=False, verbose_name='delete flag'),
        ),
    ]
